### ISSUE TITLE
threaded chunk update making large lags with Optifine

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalseTweaks#135]
Sparkc profiler :

https://spark.lucko.me/sSl1Ns30AN

Screenshot : 

![image](https://github.com/FalsePattern/FalseTweaks/assets/42176772/9e194d7e-e92f-42ee-aba1-346b68d80160)

**Comment by FalsePattern** [comment]
I also see FastCraft in the stacktrace, make sure you remove other mods before submitting a bug report about a compatibility problem.

**Comment by FalsePattern** [comment]
Should be fixed in preview 3

**Comment by quentin452** [comment]
Not fixed : https://spark.lucko.me/KJ3MUTnuHe , i don't know why but the FPS get alot of stutters when moving / destroying block even while not moving , 1000 fps  to 100 fps or less fps with the stutter

**Comment by quentin452** [comment]
Video : 

https://github.com/FalsePattern/FalseTweaks/assets/42176772/72b22bb8-8343-49ab-9d0e-93569a0f750a

spark : 

https://spark.lucko.me/LHlQtcMqqL

**Comment by quentin452** [comment]
ok so the lag is caused by fastcraft, when i disabling it all is ok

**Comment by quentin452** [comment]
l'ill watch if i find something bad in conf

**Comment by quentin452** [comment]
can't find

**Comment by quentin452** [comment]
But it seem that the lag continue to be present (in Jungle)

**Comment by makamys** [comment]
I can reproduce what is likely the same issue. It seems that with FastCraft, when the camera is moved or even a single chunk update happens, a ton of chunk updates get kicked off for some reason. I remember running into the same thing when testing ArchaicFix's occlusion tweak with FastCraft (I quickly gave up on making it work.)

In my case I have to turn off both `OCCLUSION_TWEAKS` and `THREADED_CHUNK_UPDATES` for the issue to go away. It is unclear if the same is true for Quentin.

Mod combinations I have confirmed it with:
- FT 2.7.4 + FC 1.23
- FT 2.7.4 + FC 1.23 + OF D6 + Nd 0.1.9
- FT 2.7.4 + FC 1.25 + OF E7 + Nd 0.1.9

I have also verified that it happens in a fresh instance with the default settings.

How to easily reproduce it:
1. Create a superflat world with the "Redstone ready" preset
2. Turn around 360 degrees so all chunks load
3. Wait until chunk updates drop to 0
4. Try moving the camera or placing a block. The chunk updates will jump up to the hundreds for a few seconds

Without FastCraft, moving the camera doesn't cause chunk updates and placing a block only causes 1.
https://github.com/FalsePattern/FalseTweaks/assets/13667520/447d33cf-b315-4272-9751-195cac2a396a

With FastCraft, moving the camera and placing a block both cause 100-300 chunk updates.
https://github.com/FalsePattern/FalseTweaks/assets/13667520/754b018c-f11a-4cad-b60a-bf2049ead652

**Comment by quentin452** [comment]
> I can reproduce what is likely the same issue. It seems that with FastCraft, when the camera is moved or even a single chunk update happens, a ton of chunk updates get kicked off for some reason. I remember running into the same thing when testing ArchaicFix's occlusion tweak with FastCraft (I quickly gave up on making it work.)
> 
> In my case I have to turn off both `OCCLUSION_TWEAKS` and `THREADED_CHUNK_UPDATES` for the issue to go away. It is unclear if the same is true for Quentin.
> 
> Mod combinations I have confirmed it with:
> 
>     * FT 2.7.4 + FC 1.23
> 
>     * FT 2.7.4 + FC 1.23 + OF D6 + Nd 0.1.9
> 
>     * FT 2.7.4 + FC 1.25 + OF E7 + Nd 0.1.9
> 
> 
> I have also verified that it happens in a fresh instance with the default settings.
> 
> How to easily reproduce it:
> 
>     1. Create a superflat world with the "Redstone ready" preset
> 
>     2. Turn around 360 degrees so all chunks load
> 
>     3. Wait until chunk updates drop to 0
> 
>     4. Try moving the camera or placing a block. The chunk updates will jump up to the hundreds for a few seconds
> 
> 
> Without FastCraft, moving the camera doesn't cause chunk updates and placing a block only causes 1. https://github.com/FalsePattern/FalseTweaks/assets/13667520/447d33cf-b315-4272-9751-195cac2a396a
> 
> With FastCraft, moving the camera and placing a block both cause 100-300 chunk updates. https://github.com/FalsePattern/FalseTweaks/assets/13667520/754b018c-f11a-4cad-b60a-bf2049ead652

the issue go away if OCCLUSION_TWEAKS and THREADED_CHUNK_UPDATES are disabled also for me
